### ISSUE TITLE
Shows five times higher visitor counts than Matomo

### ISSUE THREAD

**Issue by jphovila** [Findus23/plugin-ClassicCounter#1]
Hi!

The plugin works great -- except for the fact that the visitor count it shows almost five times higher than what Matomo reports. 

My Matomo version is 3.14.1, and the plugin parameters (on the img src line) are:

`module=ClassicCounter&action=svg&mode=nb_visits&idSite=1&period=day`

While Matomo dashboard reports ca. 2 000 visitors for today, the plugin shows almost 10 000.

Any idea why this could be happening?

**Comment by Findus23** [comment]
Hi,

The plugin shows the total number of visitors since the creation of the site (as with old website counters).
A per day/week/month counter might also be interesting, but I'm not sure what the best way to do it is without making all data public.

**Comment by jphovila** [comment]
Hi!

How clever of me... 🤦‍♂️ 

Thanks! 👍
